### ISSUE TITLE
Adopt to .NET Standard 2.0

### ISSUE THREAD

**Issue by anders9ustafsson** [CoreCompat/CoreCompat#11]
.NET Standard 2.0 Preview was released a few days ago. This new release has a substantially bigger API coverage, including `ICloneable` and even `System.Drawing.Color`, although most of the *System.Drawing* namespace is excluded for obvious reasons.

Would it be possible to prepare a .NET Standard 2.0 targeting library of CoreCompat that accounts for these name clashes?

**Comment by qmfrederik** [comment]
Hi @anders9ustafsson 

For .NET Standard 2.0 and .NET Core 2.0, I've prepared a new package (because of the API surface changes). Can you have a look at https://www.nuget.org/packages/CoreCompat.System.Drawing.v2 and let me know whether it works for you?

NOTE: For this version, we no longer ship libgdiplus with the NuGet package, so you'll need to make sure you've installed libgdiplus via your Linux distribution.

Let me know how it goes!

**Comment by anders9ustafsson** [comment]
Many thanks! I will test it on my project and let you know how it turns out ASAP.

**Comment by anders9ustafsson** [comment]
BTW, since I have your attention :-) Currently this package (.NET Std 1.3) is still in pre-release on NuGet. Are you planning to make an official release anytime soon?

**Comment by qmfrederik** [comment]
The original plan was to mark the `netstandard1.3` package as stable when the packages that were required to make it compile on `netstandard1.3` were accepted in Mono.

The folks over at Mono are a bit reluctant to accept all the changes, as a lot of the changes are very specific to `netstandard1.x` and no longer required on `netstandard2.0`.

All the changes required to make System.Drawing compile for `netstandard2.0` did make it into Mono, so as soon as .NET Core 2.0 is released, there'll be a stable package for `netstandard2.0`.

I'm not sure whether there will be a stable release for `netstandard1.x`; I would need to have a second look at all the changes which are required and see if it's worth trying to re-submit them as a PR for Mono.

**Comment by anders9ustafsson** [comment]
@qmfrederik With the v2 NuGet package my *System.Drawing* based .NET Standard 2.0 class library builds without errors. Hooray :-) Many thanks for your efforts with this and with the entire *CoreCompat* project!

**Comment by qmfrederik** [comment]
Thanks! FYI, all pull requests except for one needed to get a single package which builds for both `netstandard2.0` and `netstandard1.6` have landed in Mono, so I'm hoping to update the `CoreCompat.System.Drawing` package soon.

**Comment by VahidN** [comment]
I'm using the netstandard1.3 version of this library and now the .NET Standard 2.0 version doesn't provide the `ColorTranslator` anymore.
```xml
<!-- These classes are not supported on netstandard -->
<Compile Remove="$(SystemDrawingDir)System.Drawing\SystemColors.cs" />
<Compile Remove="$(SystemDrawingDir)System.Drawing\SystemPens.cs" />
<Compile Remove="$(SystemDrawingDir)System.Drawing\SystemBrushes.cs" />
<Compile Remove="$(SystemDrawingDir)System.Drawing\KnownColors.cs" />
<Compile Remove="$(SystemDrawingDir)System.Drawing\ColorTranslator.cs" />
```
Please add these classes, because old(?!) codes can't be compiled anymore.

**Comment by meysamSamanpour** [comment]
I have installed the CoreCompat.System.Drawing.v2 and uninstalled the V1. but still I cannot build the project  because I will get same error that the Color exists in both CoreCompat.System.Drawing and in netstandard version 2. Do i miss something ?

**Comment by qmfrederik** [comment]
Use [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/) instead of CoreCompat.System.Drawing.

**Comment by meysamSamanpour** [comment]
thanks for your reply. Now the ColorTranslator is not recognized. Anyone knows how can I have ColorTranslator in .net core 2?
