### ISSUE TITLE
Compatibility with Raspberry Pi 3? 

### ISSUE THREAD

**Issue by LPAMNijoel** [CoreCompat/CoreCompat#14]
May I ask a quick question? is corecompact libs compatible with ARM processor? to deploy on the raspberry pi?

**Comment by qmfrederik** [comment]
Yes, the C# (managed) code runs on ARM as well (via .NET Core or Mono) and there are ARM versions of libgdiplus.

But you should really use System.Drawing.Common instead, that's the official version of System.Drawing for .NET Core.
