### ISSUE TITLE
Double Types

### ISSUE THREAD

**Issue by kdlslyv** [CoreCompat/CoreCompat#18]
Hi, 

not quite sure if it's an issue truly conerning this great library, but when using the Color Type ( Color.White e.g), I get the notorious error:

CS0433
The type 'Color' exists in both 'CoreCompat.System.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c0a7ed9c2333b592'
and 'System.Drawing.Primitives, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

**Comment by qmfrederik** [comment]
Are you on .NET Core 2.0? If so, please give [System.Drawing.Common](https://www.nuget.org/packages/system.drawing.common/) a try; that should work better.

**Comment by kdlslyv** [comment]
Thanks a bunch for that quick reply and solution, you were completely right.
However I suppose I cannot use System.Drawing.Common on unix systems.

**Comment by qmfrederik** [comment]
@kdlslyv System.Drawing.Common is supported on Linux and macOS. Feel free to give it a try. You need to install libgdiplus, though - either via your Linux package manager or via `brew install mono-libgdiplus` on macOS.

**Comment by qmfrederik** [comment]
Closing this issue, please use System.Drawing.Common. We use it internally for macOS and Linux and haven't had any issues.
You can raise an issue at the CoreFX repo if it doesn't work for you on Mac and Linux.
