### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by samboustani** [CoreCompat/CoreCompat#25]
Error	CS2001	Source file 'C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\..\..\..\..\..\..\..\..\..\src\mono\mcs\build\common\Locale.cs' could not be found.	CoreCompat.System.Drawing(netstandard1.3)	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CSC	1	N/A
Error	CS2001	Source file 'C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\..\..\..\..\..\..\..\..\..\src\mono\mcs\build\common\MonoTODOAttribute.cs' could not be found.	CoreCompat.System.Drawing(netstandard1.3)	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CSC	1	N/A
Error	CS2001	Source file 'C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\..\..\..\..\..\..\..\..\..\src\mono\mcs\build\common\SR.cs' could not be found.	CoreCompat.System.Drawing(netstandard1.3)	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CSC	1	N/A
Error	CS2001	Source file 'C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\..\..\..\..\..\..\..\..\..\src\mono\mcs\class\referencesource\System\compmod\system\componentmodel\EditorAttribute.cs' could not be found.	CoreCompat.System.Drawing(netstandard1.3)	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CSC	1	N/A
Error	CS2001	Source file 'C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\..\..\..\..\..\..\..\..\..\src\mono\mcs\class\referencesource\mscorlib\system\runtime\interopservices\handleref.cs' could not be found.	CoreCompat.System.Drawing(netstandard1.3)	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CSC	1	N/A
Error	CS2001	Source file 'C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\..\..\..\..\..\..\..\..\..\src\mono\mcs\class\referencesource\System\compmod\system\componentmodel\ExpandableObjectConverter.cs' could not be found.	CoreCompat.System.Drawing(netstandard1.3)	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CSC	1	N/A
Error	CS2001	Source file 'C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\..\..\..\..\..\..\..\..\..\src\mono\mcs\class\referencesource\System\compmod\system\componentmodel\design\serialization\InstanceDescriptor.cs' could not be found.	CoreCompat.System.Drawing(netstandard1.3)	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CSC	1	N/A
Error	CS2001	Source file 'C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\..\..\..\..\..\..\..\..\..\src\mono\mcs\class\System\System.IO\InternalBufferOverflowException.cs' could not be found.	CoreCompat.System.Drawing(netstandard1.3)	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CSC	1	N/A
Error	CS2001	Source file 'C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\..\..\..\..\..\..\..\..\..\src\mono\mcs\class\referencesource\System\compmod\system\componentmodel\InvalidEnumArgumentException.cs' could not be found.	CoreCompat.System.Drawing(netstandard1.3)	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CSC	1	N/A
Error	CS2001	Source file 'C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\..\..\..\..\..\..\..\..\..\src\mono\mcs\class\referencesource\mscorlib\system\ICloneable.cs' could not be found.	CoreCompat.System.Drawing(netstandard1.3)	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CSC	1	N/A
Error	CS2001	Source file 'C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\..\..\..\..\..\..\..\..\..\src\mono\mcs\class\System\ReferenceSources\SR.cs' could not be found.	CoreCompat.System.Drawing(netstandard1.3)	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CSC	1	N/A
Error	NU1605	Detected package downgrade: Microsoft.Win32.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version. 
 CoreCompat.System.Drawing -> NETStandard.Library 1.6.1 -> Microsoft.Win32.Primitives (>= 4.3.0) 
 CoreCompat.System.Drawing -> Microsoft.Win32.Primitives (>= 4.0.1)	CoreCompat.System.Drawing	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CoreCompat.System.Drawing.csproj	1	
Error	NU1605	Detected package downgrade: System.IO.FileSystem from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version. 
 CoreCompat.System.Drawing -> NETStandard.Library 1.6.1 -> System.IO.FileSystem (>= 4.3.0) 
 CoreCompat.System.Drawing -> System.IO.FileSystem (>= 4.0.1)	CoreCompat.System.Drawing	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CoreCompat.System.Drawing.csproj	1	
Error	NU1605	Detected package downgrade: System.Runtime.Extensions from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version. 
 CoreCompat.System.Drawing -> NETStandard.Library 1.6.1 -> System.Runtime.Extensions (>= 4.3.0) 
 CoreCompat.System.Drawing -> System.Runtime.Extensions (>= 4.1.0)	CoreCompat.System.Drawing	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CoreCompat.System.Drawing.csproj	1	
Error	NU1605	Detected package downgrade: System.Runtime.InteropServices from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version. 
 CoreCompat.System.Drawing -> NETStandard.Library 1.6.1 -> System.Runtime.InteropServices (>= 4.3.0) 
 CoreCompat.System.Drawing -> System.Runtime.InteropServices (>= 4.1.0)	CoreCompat.System.Drawing	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CoreCompat.System.Drawing.csproj	1	
Error	NU1605	Detected package downgrade: System.Runtime.InteropServices.RuntimeInformation from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version. 
 CoreCompat.System.Drawing -> NETStandard.Library 1.6.1 -> System.Runtime.InteropServices.RuntimeInformation (>= 4.3.0) 
 CoreCompat.System.Drawing -> System.Runtime.InteropServices.RuntimeInformation (>= 4.0.0)	CoreCompat.System.Drawing	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CoreCompat.System.Drawing.csproj	1	
Error	NU1605	Detected package downgrade: System.Text.Encoding.Extensions from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version. 
 CoreCompat.System.Drawing -> NETStandard.Library 1.6.1 -> System.Text.Encoding.Extensions (>= 4.3.0) 
 CoreCompat.System.Drawing -> System.Text.Encoding.Extensions (>= 4.0.11)	CoreCompat.System.Drawing	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CoreCompat.System.Drawing.csproj	1	
Error	NU1605	Detected package downgrade: System.Text.RegularExpressions from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version. 
 CoreCompat.System.Drawing -> NETStandard.Library 1.6.1 -> System.Text.RegularExpressions (>= 4.3.0) 
 CoreCompat.System.Drawing -> System.Text.RegularExpressions (>= 4.1.0)	CoreCompat.System.Drawing	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CoreCompat.System.Drawing.csproj	1	
Error	NU1605	Detected package downgrade: System.Threading from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version. 
 CoreCompat.System.Drawing -> NETStandard.Library 1.6.1 -> System.Threading (>= 4.3.0) 
 CoreCompat.System.Drawing -> System.Threading (>= 4.0.11)	CoreCompat.System.Drawing	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CoreCompat.System.Drawing.csproj	1	
Error	NU1605	Detected package downgrade: Microsoft.Win32.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version. 
 CoreCompat.System.Drawing -> NETStandard.Library 1.6.1 -> Microsoft.Win32.Primitives (>= 4.3.0) 
 CoreCompat.System.Drawing -> Microsoft.Win32.Primitives (>= 4.0.1)	CoreCompat.System.Drawing	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CoreCompat.System.Drawing.csproj	1	
Error	NU1605	Detected package downgrade: System.IO.FileSystem from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version. 
 CoreCompat.System.Drawing -> NETStandard.Library 1.6.1 -> System.IO.FileSystem (>= 4.3.0) 
 CoreCompat.System.Drawing -> System.IO.FileSystem (>= 4.0.1)	CoreCompat.System.Drawing	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CoreCompat.System.Drawing.csproj	1	
Error	NU1605	Detected package downgrade: System.Runtime.Extensions from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version. 
 CoreCompat.System.Drawing -> NETStandard.Library 1.6.1 -> System.Runtime.Extensions (>= 4.3.0) 
 CoreCompat.System.Drawing -> System.Runtime.Extensions (>= 4.1.0)	CoreCompat.System.Drawing	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CoreCompat.System.Drawing.csproj	1	
Error	NU1605	Detected package downgrade: System.Runtime.InteropServices from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version. 
 CoreCompat.System.Drawing -> NETStandard.Library 1.6.1 -> System.Runtime.InteropServices (>= 4.3.0) 
 CoreCompat.System.Drawing -> System.Runtime.InteropServices (>= 4.1.0)	CoreCompat.System.Drawing	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CoreCompat.System.Drawing.csproj	1	
Error	NU1605	Detected package downgrade: System.Runtime.InteropServices.RuntimeInformation from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version. 
 CoreCompat.System.Drawing -> NETStandard.Library 1.6.1 -> System.Runtime.InteropServices.RuntimeInformation (>= 4.3.0) 
 CoreCompat.System.Drawing -> System.Runtime.InteropServices.RuntimeInformation (>= 4.0.0)	CoreCompat.System.Drawing	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CoreCompat.System.Drawing.csproj	1	
Error	NU1605	Detected package downgrade: System.Text.Encoding.Extensions from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version. 
 CoreCompat.System.Drawing -> NETStandard.Library 1.6.1 -> System.Text.Encoding.Extensions (>= 4.3.0) 
 CoreCompat.System.Drawing -> System.Text.Encoding.Extensions (>= 4.0.11)	CoreCompat.System.Drawing	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CoreCompat.System.Drawing.csproj	1	
Error	NU1605	Detected package downgrade: System.Text.RegularExpressions from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version. 
 CoreCompat.System.Drawing -> NETStandard.Library 1.6.1 -> System.Text.RegularExpressions (>= 4.3.0) 
 CoreCompat.System.Drawing -> System.Text.RegularExpressions (>= 4.1.0)	CoreCompat.System.Drawing	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CoreCompat.System.Drawing.csproj	1	
Error	NU1605	Detected package downgrade: System.Threading from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version. 
 CoreCompat.System.Drawing -> NETStandard.Library 1.6.1 -> System.Threading (>= 4.3.0) 
 CoreCompat.System.Drawing -> System.Threading (>= 4.0.11)	CoreCompat.System.Drawing	C:\Users\Sam\Documents\Development\Downloads\CoreCompat-master\src\CoreCompat.System.Drawing\CoreCompat.System.Drawing.csproj	1

**Comment by qmfrederik** [comment]
CoreCompat.System.Drawing has been superseded by System.Drawing.Common.

Please use System.Drawing.Common. Thanks!
