### ISSUE TITLE
Can you make this work on Xamarin.Forms?

### ISSUE THREAD

**Issue by Emasoft** [CoreCompat/CoreCompat#5]
Having this working on Xamarin.Forms for iOS and Android, MacOs, etc. would be really awesome.

**Comment by qmfrederik** [comment]
It should work once netstandard2.0 is available: Xamarin should support netstandard2.0, and I plan to make the library compatible with netstandard2.0

The remaining challenge would be to get libgdiplus run on the Xamarin platforms.

**Comment by JimSEOW** [comment]
We need to examine the use case to support Xamarin.Forms. For Windows phone, it is the same as supporting UWP for porting purpose, For Android and iOS, currently I could not see a good use case right now, perhaps someone could provide some relevant examples

**Comment by aleGuardiola** [comment]
Any news with Xamarin.Android and Xamarin.IOS??

**Comment by qmfrederik** [comment]
There's now a version of System.Drawing in the official .NET Core repositories (as System.Drawing.Common). It supports netstandard2.0 so I guess it also supports Xamarin, although I haven't tried.

I'm not planning to do additional work on System.Drawing here, but feel free to ask in the Xamarin/CoreFX repos.
