### ISSUE TITLE
Is there interest to support UWP? 

### ISSUE THREAD

**Issue by JimSEOW** [CoreCompat/CoreCompat#6]
I wonder if there is sufficient interest to make System.Drawing available for UWP. For winform devleoper, this could ease the porting from winform to UWP. This would allow the developer to focus on non System.Drawing related code First and then porting the System.Drawing relevant parts to Windows.UI. 

This may accelerate more porting of WinForm application to UWP App.

**Comment by qmfrederik** [comment]
I don't see why this shouldn't work, as the library currently builds on .NET Core it should also build for UWP.

The tricky part may be to get `libgdiplus` to compile for UWP, haven't  looked into that.

Happy to accept a PR/answer questions related to UWP but don't think I'll work on it any time soon.

**Comment by qmfrederik** [comment]
Just one more note:
- UWP should support netstandard2.0 (https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/) 
- I plan to make the library compatible with netstandard2.0

The remaining challenge would be to get libgdiplus run on UWP.

**Comment by JimSEOW** [comment]
Is this the [libgdiplus](https://github.com/mono/libgdiplus) source?

What you are doing is critical as part of the whole picture of cross platform UI. There are different projects which attempt to support this vision e.g. SkiaSharp (Vector graphics), Avalon (WPF XAML). 

.NET Core is advertised as Cross-platform service. How to bridge this service and UI is currently evolving. Your library will definitely help some ecosystems to port and to learn as one venture from one platform  to another.

**Comment by qmfrederik** [comment]
Yes, that's the libgdiplus source, although I've [forked it to support compiling libgdiplus on OSX](https://github.com/CoreCompat/libgdiplus)

**Comment by qmfrederik** [comment]
For UWP support going forward, your best bet is to ask in the CoreFX repos where System.Drawing.Common is maintained - that's the official version of System.Drawing for .NET Core.
