### ISSUE TITLE
Antialias of image bitmap using DotNet Core

### ISSUE THREAD

**Issue by jasonsturges** [CoreCompat/CoreCompat#8]
DotNet Core apps using CoreCompat's System.Drawing.Image do not appear antialiased on Mac.

Not entirely sure I'm aware of the internals; however, on Windows I believe this is using GDI+, whereas on Mac libgdiplus.dylib uses Cairo.  

On PC, resizing an image looks great:

![resized-pc](https://cloud.githubusercontent.com/assets/1213591/22608122/a6f50020-ea20-11e6-9cde-420cb5f67c8f.png)

On Mac OS X using the exact same code, appears as:

![resized-mac](https://cloud.githubusercontent.com/assets/1213591/22608142/c4fe506c-ea20-11e6-85aa-e1d9898a56f0.png)

Any insight whether this issue is internal to CoreCompat or library dependency?

Code used to resize the above images:

```
using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;

namespace DrawingTest
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            var image = Image.FromFile(@"/users/jsturges/master.png");
            var resized = ResizeImage(image, 256, 256);
            resized.Save(@"/users/jsturges/resized-mac.png");
        }

        public static Bitmap ResizeImage(Image image, int width, int height)
        {
            var ratioX = width / (float)image.Width;
            var ratioY = width / (float)image.Height;
            var ratio = Math.Min(ratioX, ratioY);

            var scaleWidth = (int)Math.Floor(image.Width * ratio);
            var scaleHeight = (int)Math.Floor(image.Height * ratio);

            var bitmap = new Bitmap(scaleWidth, scaleHeight, PixelFormat.Format32bppRgb);

            using (var graphics = Graphics.FromImage(bitmap))
            {
                graphics.CompositingMode = CompositingMode.SourceCopy;
                graphics.CompositingQuality = CompositingQuality.HighQuality;
                graphics.InterpolationMode = InterpolationMode.HighQualityBicubic;
                graphics.SmoothingMode = SmoothingMode.HighQuality;
                graphics.PixelOffsetMode = PixelOffsetMode.HighQuality;

                using (var wrapMode = new ImageAttributes())
                {
                    wrapMode.SetWrapMode(WrapMode.TileFlipXY);
                    var rect = new Rectangle(0, 0, scaleWidth, scaleHeight);
                    graphics.DrawImage(image, rect, 0, 0, image.Width, image.Height, GraphicsUnit.Pixel, wrapMode);
                }
            }

            return bitmap;
        }
    }
}
```

Original 3756 x 3756 pixel image used to resize:

![master](https://cloud.githubusercontent.com/assets/1213591/22608107/9800f7ae-ea20-11e6-988d-2b09e109885d.png)

**Comment by qmfrederik** [comment]
@jasonsturges I would need to check, I didn't run this kind of test yet.

If you are able to, could you try to run the same transformation using Mono on Mac and report back the results?

CoreCompat.System.Drawing is using the Mono code beneath the covers, so it would be interested to see if this issue is present in Mono as well, or whether it's related to how we compile libgdiplus.

**Comment by jasonsturges** [comment]
@qmfrederik Mono does have the same issue.  Root cause is libgdiplus; so, not really an issue with CoreCompat.  

Sorry - thanks for the info.

**Comment by jasonsturges** [comment]
This works perfectly by adding the reference:

- `runtime.osx.10.10-x64.CoreCompat.System.Drawing` 
- https://www.nuget.org/packages/runtime.osx.10.10-x64.CoreCompat.System.Drawing/1.0.1-beta004

This resolves antialias issues, as well as dependency issues with libgdiplus on macOs.

**Comment by wcrooy** [comment]
@qmfrederik I've the same issue but then on linux with the linux native libs. (https://www.nuget.org/packages/runtime.linux-x64.CoreCompat.System.Drawing )
Anything which can be done about that?
Unfortunately I'm not able to directly test it with mono.
